/* ===========================================================================
   build-arabic.mjs
   מייצר src/data/arabic.ts — מפת תרגומים לערבית (MSA) לכל מזהה.
   התרגומים אוטומטיים — מומלץ לעבור ולתקן ידנית במקרה הצורך.
   מספרים אינם כאן: בזמן ריצה משתמשים בספרה עצמה (TTS ar קורא אותה כמילה).

   הרצה: node scripts/build-arabic.mjs   (או: npm run arabic)
   =========================================================================== */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const VOCAB_TS = path.join(ROOT, 'src', 'data', 'vocabulary.generated.ts');
const OUT_TS = path.join(ROOT, 'src', 'data', 'arabic.ts');

/** מילון תרגומים אוטומטי (id -> ערבית). */
const AR = {
  // דמויות
  characters_abyr: 'فارِس', characters_gnb: 'لِصّ', characters_zomby: 'زُومبي',
  characters_chyzr: 'كائِن فَضائي', characters_chyl: 'جُندي', characters_lytzn: 'مُهَرِّج',
  characters_mkshf: 'ساحِر', characters_mlk: 'مَلِك', characters_mlkh: 'مَلِكة',
  characters_kosm: 'ساحِر', characters_robot: 'رُوبوت', characters_shf: 'طاهٍ',
  // חיות — בר
  animals_aryh: 'أسَد', animals_arnb: 'أرنَب', animals_jyrph: 'زَرافة', animals_gml: 'جَمَل',
  animals_gorylh: 'غُوريلا', animals_dob: 'دُبّ', animals_hypopotm: 'فَرَس النَّهر',
  animals_zbrh: 'حِمار وَحشي', animals_chtol: 'قِطّة', animals_klb: 'كَلب', animals_nchsh: 'ثُعبان',
  animals_nmr: 'نَمِر', animals_snay: 'سِنجاب', animals_atlf: 'خُفّاش', animals_akbr: 'فَأر',
  animals_pyl: 'فِيل', animals_pyngoyn: 'بِطريق', animals_pndh: 'باندا', animals_tzby: 'غَزال',
  animals_tzprda: 'ضِفدَع', animals_tzb: 'سُلَحفاة', animals_koalh: 'كُوالا', animals_kof: 'قِرد',
  animals_shoal: 'ثَعلَب', animals_tnyn: 'تِمساح',
  // חיות — חווה
  animals_chzyr: 'خِنزير', animals_chmor: 'حِمار', animals_kbshh: 'خَروف', animals_sos: 'حِصان',
  animals_az: 'ماعِز', animals_prh: 'بَقَرة', animals_trngol: 'دِيك',
  // חיות — ים
  animals_dg: 'سَمَكة', animals_dolpyn: 'دُلفين', animals_klb_ym: 'فُقمة', animals_krysh: 'قِرش',
  animals_sos_ym: 'حِصان البَحر', animals_tmnon: 'أخطَبوط',
  // חיות — ציפורים
  animals_broz: 'بَطّة', animals_ynshof: 'بُومة', animals_yonh: 'حَمامة',
  animals_plmngo: 'فلامِنغو', animals_toky: 'بَبّغاء',
  // ירקות
  vegetables_abokdo: 'أفوكادو', vegetables_brokoly: 'بروكلي', vegetables_btzl: 'بَصَل',
  vegetables_gzr: 'جَزَر', vegetables_gmbh: 'فُلفُل', vegetables_dlat: 'يَقطين',
  vegetables_chtzyl: 'باذِنجان', vegetables_agbnyh: 'طَماطِم', vegetables_ptryh: 'فِطر',
  vegetables_tyrs: 'ذُرة', vegetables_tpoch_admh: 'بَطاطا',
  // מוזיקה
  music_aznyot: 'سَمّاعات', music_gytrh: 'جِيتار', music_chtzotzrh: 'بُوق', music_chlyl: 'ناي',
  music_knor: 'كَمان', music_lhkh: 'فِرقة', music_mykropon: 'مِيكروفون', music_sksopon: 'ساكسُفون',
  music_psntr: 'بِيانو', music_rmkol: 'مُكَبِّر صَوت', music_to: 'نُوتة', music_tpym: 'طُبول',
  // פירות
  fruits_ags: 'إجّاص', fruits_anns: 'أناناس', fruits_bnnh: 'مَوز', fruits_dbdbn: 'كَرَز',
  fruits_lymon: 'لَيمون', fruits_mngo: 'مانجو', fruits_anbym: 'عِنَب', fruits_rmon: 'رُمّان',
  fruits_tpoz: 'بُرتُقال', fruits_tpoch: 'تُفّاح', fruits_tot: 'فَراولة',
  // קינוחים
  desserts_artyk: 'آيس كريم', desserts_hmborgr: 'هامبرغر', desserts_mylkshyk: 'ميلك شيك',
  desserts_nknykyh_blchmnyh: 'هوت دوغ', desserts_skryh_al_mkl: 'مَصّاصة', desserts_aogyh: 'بِسكويت',
  desserts_aogh: 'كَعكة', desserts_pytzh: 'بيتزا', desserts_popkorn: 'فُشار', desserts_chyps: 'بطاطا مقلية',
  desserts_kolh: 'كولا', desserts_shokold: 'شوكولاتة',
  // צבעים
  color_red: 'أحمَر', color_blue: 'أزرَق', color_yellow: 'أصفَر', color_green: 'أخضَر',
  color_orange: 'بُرتُقالي', color_purple: 'بَنَفسَجي', color_pink: 'وَردي', color_black: 'أسوَد',
  color_white: 'أبيَض', color_brown: 'بُنّي',
};

async function main() {
  // ולידציה מול אוצר המילים שנוצר
  let vocabIds = [];
  try {
    const txt = await fs.readFile(VOCAB_TS, 'utf8');
    vocabIds = [...txt.matchAll(/"id":\s*"([^"]+)"/g)].map((m) => m[1]);
  } catch {
    console.warn('⚠️  vocabulary.generated.ts לא נמצא — הרץ npm run manifest קודם.');
  }
  const missing = vocabIds.filter((id) => !AR[id]);
  if (missing.length) console.warn(`⚠️  חסר תרגום ערבי ל-${missing.length} פריטים:`, missing);

  const out = `/* AUTO-GENERATED by scripts/build-arabic.mjs — תרגומים אוטומטיים (MSA).
   ניתן לערוך ידנית, אך הרצת npm run arabic תדרוס. עדיף לעדכן את המילון בסקריפט.
   מספרים אינם כאן — בזמן ריצה משתמשים בספרה עצמה. */

export const ARABIC: Record<string, string> = ${JSON.stringify(AR, null, 2)};

/** תרגום ערבי לפריט (לפי id). מספרים: הספרה עצמה. */
export function arabicText(id: string, fallback: string): string {
  if (id.startsWith('num_')) return id.slice(4);
  return ARABIC[id] ?? fallback;
}
`;
  await fs.writeFile(OUT_TS, out, 'utf8');
  console.log(`✅ נכתב ${path.relative(ROOT, OUT_TS)} (${Object.keys(AR).length} תרגומים).`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
