/* AUTO-GENERATED by scripts/build-manifest.mjs — אל תערוך ידנית.
   הרץ: npm run manifest */
import type { VocabItem } from './types';

export const VOCABULARY: VocabItem[] = [
  {
    "id": "characters_abyr",
    "he": "אַבִּיר",
    "categoryId": "characters",
    "image": "/images/characters/characters_abyr.webp"
  },
  {
    "id": "characters_gnb",
    "he": "גָּנַב",
    "categoryId": "characters",
    "image": "/images/characters/characters_gnb.webp"
  },
  {
    "id": "characters_zomby",
    "he": "זוֹמְבִּי",
    "categoryId": "characters",
    "image": "/images/characters/characters_zomby.webp"
  },
  {
    "id": "characters_chyzr",
    "he": "חַיְזָר",
    "categoryId": "characters",
    "image": "/images/characters/characters_chyzr.webp"
  },
  {
    "id": "characters_chyl",
    "he": "חַיָּל",
    "categoryId": "characters",
    "image": "/images/characters/characters_chyl.webp"
  },
  {
    "id": "characters_lytzn",
    "he": "לֵיצָן",
    "categoryId": "characters",
    "image": "/images/characters/characters_lytzn.webp"
  },
  {
    "id": "characters_mkshf",
    "he": "מְכַשֵּׁף",
    "categoryId": "characters",
    "image": "/images/characters/characters_mkshf.webp"
  },
  {
    "id": "characters_mlk",
    "he": "מֶלֶךְ",
    "categoryId": "characters",
    "image": "/images/characters/characters_mlk.webp"
  },
  {
    "id": "characters_mlkh",
    "he": "מַלְכָּה",
    "categoryId": "characters",
    "image": "/images/characters/characters_mlkh.webp"
  },
  {
    "id": "characters_kosm",
    "he": "קוֹסֵם",
    "categoryId": "characters",
    "image": "/images/characters/characters_kosm.webp"
  },
  {
    "id": "characters_robot",
    "he": "רוֹבּוֹט",
    "categoryId": "characters",
    "image": "/images/characters/characters_robot.webp"
  },
  {
    "id": "characters_shf",
    "he": "שֵׁף",
    "categoryId": "characters",
    "image": "/images/characters/characters_shf.webp"
  },
  {
    "id": "animals_aryh",
    "he": "אַרְיֵה",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_aryh.webp"
  },
  {
    "id": "animals_arnb",
    "he": "אַרְנָב",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_arnb.webp"
  },
  {
    "id": "animals_jyrph",
    "he": "ג'ִירָפָה",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_jyrph.webp"
  },
  {
    "id": "animals_gml",
    "he": "גָמָל",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_gml.webp"
  },
  {
    "id": "animals_gorylh",
    "he": "גּוֹרִילָה",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_gorylh.webp"
  },
  {
    "id": "animals_dob",
    "he": "דוֹב",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_dob.webp"
  },
  {
    "id": "animals_hypopotm",
    "he": "הִיפּוֹפּוֹטָם",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_hypopotm.webp"
  },
  {
    "id": "animals_zbrh",
    "he": "זֶבְּרָה",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_zbrh.webp"
  },
  {
    "id": "animals_chtol",
    "he": "חָתוּל",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_chtol.webp"
  },
  {
    "id": "animals_klb",
    "he": "כֶּלֶב",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_klb.webp"
  },
  {
    "id": "animals_nchsh",
    "he": "נָחָשׁ",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_nchsh.webp"
  },
  {
    "id": "animals_nmr",
    "he": "נָמֵר",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_nmr.webp"
  },
  {
    "id": "animals_snay",
    "he": "סְנָאִי",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_snay.webp"
  },
  {
    "id": "animals_atlf",
    "he": "עֲטַלֵּף",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_atlf.webp"
  },
  {
    "id": "animals_akbr",
    "he": "עַכְבָּר",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_akbr.webp"
  },
  {
    "id": "animals_pyl",
    "he": "פִּיל",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_pyl.webp"
  },
  {
    "id": "animals_pyngoyn",
    "he": "פִּינְגְּוִין",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_pyngoyn.webp"
  },
  {
    "id": "animals_pndh",
    "he": "פַּנְדָּה",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_pndh.webp"
  },
  {
    "id": "animals_tzby",
    "he": "צְבִי",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_tzby.webp"
  },
  {
    "id": "animals_tzprda",
    "he": "צְפַרְדֵּעַ",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_tzprda.webp"
  },
  {
    "id": "animals_tzb",
    "he": "צָב",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_tzb.webp"
  },
  {
    "id": "animals_koalh",
    "he": "קוֹאָלָה",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_koalh.webp"
  },
  {
    "id": "animals_kof",
    "he": "קוֹף",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_kof.webp"
  },
  {
    "id": "animals_shoal",
    "he": "שׁוּעָל",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_shoal.webp"
  },
  {
    "id": "animals_tnyn",
    "he": "תַנִין",
    "categoryId": "animals",
    "subgroup": "wild",
    "image": "/images/animals/animals_tnyn.webp"
  },
  {
    "id": "animals_chzyr",
    "he": "חֲזִיר",
    "categoryId": "animals",
    "subgroup": "farm",
    "image": "/images/animals/animals_chzyr.webp"
  },
  {
    "id": "animals_chmor",
    "he": "חֲמוֹר",
    "categoryId": "animals",
    "subgroup": "farm",
    "image": "/images/animals/animals_chmor.webp"
  },
  {
    "id": "animals_kbshh",
    "he": "כִּבְשָׂה",
    "categoryId": "animals",
    "subgroup": "farm",
    "image": "/images/animals/animals_kbshh.webp"
  },
  {
    "id": "animals_sos",
    "he": "סוּס",
    "categoryId": "animals",
    "subgroup": "farm",
    "image": "/images/animals/animals_sos.webp"
  },
  {
    "id": "animals_az",
    "he": "עֵז",
    "categoryId": "animals",
    "subgroup": "farm",
    "image": "/images/animals/animals_az.webp"
  },
  {
    "id": "animals_prh",
    "he": "פָּרָה",
    "categoryId": "animals",
    "subgroup": "farm",
    "image": "/images/animals/animals_prh.webp"
  },
  {
    "id": "animals_trngol",
    "he": "תַרְנְגוֹל",
    "categoryId": "animals",
    "subgroup": "farm",
    "image": "/images/animals/animals_trngol.webp"
  },
  {
    "id": "animals_dg",
    "he": "דָג",
    "categoryId": "animals",
    "subgroup": "sea",
    "image": "/images/animals/animals_dg.webp"
  },
  {
    "id": "animals_dolpyn",
    "he": "דוֹלפִין",
    "categoryId": "animals",
    "subgroup": "sea",
    "image": "/images/animals/animals_dolpyn.webp"
  },
  {
    "id": "animals_klb_ym",
    "he": "כֶּלֶב יָם",
    "categoryId": "animals",
    "subgroup": "sea",
    "image": "/images/animals/animals_klb_ym.webp"
  },
  {
    "id": "animals_krysh",
    "he": "כָּרִישׁ",
    "categoryId": "animals",
    "subgroup": "sea",
    "image": "/images/animals/animals_krysh.webp"
  },
  {
    "id": "animals_sos_ym",
    "he": "סוּס יָם",
    "categoryId": "animals",
    "subgroup": "sea",
    "image": "/images/animals/animals_sos_ym.webp"
  },
  {
    "id": "animals_tmnon",
    "he": "תָמְנוּן",
    "categoryId": "animals",
    "subgroup": "sea",
    "image": "/images/animals/animals_tmnon.webp"
  },
  {
    "id": "animals_broz",
    "he": "בַּרְוָז",
    "categoryId": "animals",
    "subgroup": "birds",
    "image": "/images/animals/animals_broz.webp"
  },
  {
    "id": "animals_ynshof",
    "he": "יַנשׁוּף",
    "categoryId": "animals",
    "subgroup": "birds",
    "image": "/images/animals/animals_ynshof.webp"
  },
  {
    "id": "animals_yonh",
    "he": "יוֹנָה",
    "categoryId": "animals",
    "subgroup": "birds",
    "image": "/images/animals/animals_yonh.webp"
  },
  {
    "id": "animals_plmngo",
    "he": "פְלָמֶנְגּוֹ",
    "categoryId": "animals",
    "subgroup": "birds",
    "image": "/images/animals/animals_plmngo.webp"
  },
  {
    "id": "animals_toky",
    "he": "תוּכִּי",
    "categoryId": "animals",
    "subgroup": "birds",
    "image": "/images/animals/animals_toky.webp"
  },
  {
    "id": "vegetables_abokdo",
    "he": "אָבוֹקָדוֹ",
    "categoryId": "vegetables",
    "image": "/images/vegetables/vegetables_abokdo.webp"
  },
  {
    "id": "vegetables_brokoly",
    "he": "בְּרוֹקוֹלִי",
    "categoryId": "vegetables",
    "image": "/images/vegetables/vegetables_brokoly.webp"
  },
  {
    "id": "vegetables_btzl",
    "he": "בָּצָל",
    "categoryId": "vegetables",
    "image": "/images/vegetables/vegetables_btzl.webp"
  },
  {
    "id": "vegetables_gzr",
    "he": "גֶּזֶר",
    "categoryId": "vegetables",
    "image": "/images/vegetables/vegetables_gzr.webp"
  },
  {
    "id": "vegetables_gmbh",
    "he": "גַּמְבָּה",
    "categoryId": "vegetables",
    "image": "/images/vegetables/vegetables_gmbh.webp"
  },
  {
    "id": "vegetables_dlat",
    "he": "דְּלַעַת",
    "categoryId": "vegetables",
    "image": "/images/vegetables/vegetables_dlat.webp"
  },
  {
    "id": "vegetables_chtzyl",
    "he": "חָצִיל",
    "categoryId": "vegetables",
    "image": "/images/vegetables/vegetables_chtzyl.webp"
  },
  {
    "id": "vegetables_agbnyh",
    "he": "עַגְבָנִיָּה",
    "categoryId": "vegetables",
    "image": "/images/vegetables/vegetables_agbnyh.webp"
  },
  {
    "id": "vegetables_ptryh",
    "he": "פִּטְרִיָּה",
    "categoryId": "vegetables",
    "image": "/images/vegetables/vegetables_ptryh.webp"
  },
  {
    "id": "vegetables_tyrs",
    "he": "תִּירָס",
    "categoryId": "vegetables",
    "image": "/images/vegetables/vegetables_tyrs.webp"
  },
  {
    "id": "vegetables_tpoch_admh",
    "he": "תַּפּוּחַ אֲדָמָה",
    "categoryId": "vegetables",
    "image": "/images/vegetables/vegetables_tpoch_admh.webp"
  },
  {
    "id": "music_aznyot",
    "he": "אָזְנִיּוֹת",
    "categoryId": "music",
    "image": "/images/music/music_aznyot.webp"
  },
  {
    "id": "music_gytrh",
    "he": "גִּיטָרָה",
    "categoryId": "music",
    "image": "/images/music/music_gytrh.webp"
  },
  {
    "id": "music_chtzotzrh",
    "he": "חֲצוֹצְרָה",
    "categoryId": "music",
    "image": "/images/music/music_chtzotzrh.webp"
  },
  {
    "id": "music_chlyl",
    "he": "חָלִיל",
    "categoryId": "music",
    "image": "/images/music/music_chlyl.webp"
  },
  {
    "id": "music_knor",
    "he": "כִּנּוֹר",
    "categoryId": "music",
    "image": "/images/music/music_knor.webp"
  },
  {
    "id": "music_lhkh",
    "he": "לַהֲקָה",
    "categoryId": "music",
    "image": "/images/music/music_lhkh.webp"
  },
  {
    "id": "music_mykropon",
    "he": "מִיקְרוֹפוֹן",
    "categoryId": "music",
    "image": "/images/music/music_mykropon.webp"
  },
  {
    "id": "music_sksopon",
    "he": "סַקְסוֹפוֹן",
    "categoryId": "music",
    "image": "/images/music/music_sksopon.webp"
  },
  {
    "id": "music_psntr",
    "he": "פְּסַנְתֵּר",
    "categoryId": "music",
    "image": "/images/music/music_psntr.webp"
  },
  {
    "id": "music_rmkol",
    "he": "רַמְקוֹל",
    "categoryId": "music",
    "image": "/images/music/music_rmkol.webp"
  },
  {
    "id": "music_to",
    "he": "תָּו",
    "categoryId": "music",
    "image": "/images/music/music_to.webp"
  },
  {
    "id": "music_tpym",
    "he": "תֻּפִּים",
    "categoryId": "music",
    "image": "/images/music/music_tpym.webp"
  },
  {
    "id": "fruits_ags",
    "he": "אַגָּס",
    "categoryId": "fruits",
    "image": "/images/fruits/fruits_ags.webp"
  },
  {
    "id": "fruits_anns",
    "he": "אָנָנָס",
    "categoryId": "fruits",
    "image": "/images/fruits/fruits_anns.webp"
  },
  {
    "id": "fruits_bnnh",
    "he": "בָּנָנָה",
    "categoryId": "fruits",
    "image": "/images/fruits/fruits_bnnh.webp"
  },
  {
    "id": "fruits_dbdbn",
    "he": "דֻּבְדְּבָן",
    "categoryId": "fruits",
    "image": "/images/fruits/fruits_dbdbn.webp"
  },
  {
    "id": "fruits_lymon",
    "he": "לִימוֹן",
    "categoryId": "fruits",
    "image": "/images/fruits/fruits_lymon.webp"
  },
  {
    "id": "fruits_mngo",
    "he": "מַנְגּוֹ",
    "categoryId": "fruits",
    "image": "/images/fruits/fruits_mngo.webp"
  },
  {
    "id": "fruits_anbym",
    "he": "עֲנָבִים",
    "categoryId": "fruits",
    "image": "/images/fruits/fruits_anbym.webp"
  },
  {
    "id": "fruits_rmon",
    "he": "רִמּוֹן",
    "categoryId": "fruits",
    "image": "/images/fruits/fruits_rmon.webp"
  },
  {
    "id": "fruits_tpoz",
    "he": "תַּפּוּז",
    "categoryId": "fruits",
    "image": "/images/fruits/fruits_tpoz.webp"
  },
  {
    "id": "fruits_tpoch",
    "he": "תַּפּוּחַ",
    "categoryId": "fruits",
    "image": "/images/fruits/fruits_tpoch.webp"
  },
  {
    "id": "fruits_tot",
    "he": "תּוּת",
    "categoryId": "fruits",
    "image": "/images/fruits/fruits_tot.webp"
  },
  {
    "id": "desserts_artyk",
    "he": "אַרְטִיק",
    "categoryId": "desserts",
    "image": "/images/desserts/desserts_artyk.webp"
  },
  {
    "id": "desserts_hmborgr",
    "he": "הַמְבּוּרְגֵּר",
    "categoryId": "desserts",
    "image": "/images/desserts/desserts_hmborgr.webp"
  },
  {
    "id": "desserts_mylkshyk",
    "he": "מִילְקְשֵׁיְק",
    "categoryId": "desserts",
    "image": "/images/desserts/desserts_mylkshyk.webp"
  },
  {
    "id": "desserts_nknykh_blchmnyh",
    "he": "נַקְנִיקָהּ בְּלַחְמָנִיָּה",
    "categoryId": "desserts",
    "image": "/images/desserts/desserts_nknykh_blchmnyh.webp"
  },
  {
    "id": "desserts_skryh_al_mkl",
    "he": "סֻכָּרִיָּה עַל מַקֵּל",
    "categoryId": "desserts",
    "image": "/images/desserts/desserts_skryh_al_mkl.webp"
  },
  {
    "id": "desserts_aogyh",
    "he": "עוּגִיָּה",
    "categoryId": "desserts",
    "image": "/images/desserts/desserts_aogyh.webp"
  },
  {
    "id": "desserts_aogh",
    "he": "עוּגָה",
    "categoryId": "desserts",
    "image": "/images/desserts/desserts_aogh.webp"
  },
  {
    "id": "desserts_pytzh",
    "he": "פִּיצָה",
    "categoryId": "desserts",
    "image": "/images/desserts/desserts_pytzh.webp"
  },
  {
    "id": "desserts_popkorn",
    "he": "פּוֹפְּקוֹרְן",
    "categoryId": "desserts",
    "image": "/images/desserts/desserts_popkorn.webp"
  },
  {
    "id": "desserts_chyps",
    "he": "צִ'יפְּס",
    "categoryId": "desserts",
    "image": "/images/desserts/desserts_chyps.webp"
  },
  {
    "id": "desserts_kolh",
    "he": "קוֹלָה",
    "categoryId": "desserts",
    "image": "/images/desserts/desserts_kolh.webp"
  },
  {
    "id": "desserts_shokold",
    "he": "שׁוֹקוֹלָד",
    "categoryId": "desserts",
    "image": "/images/desserts/desserts_shokold.webp"
  }
];
